name: Build and Deploy

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches:
      - main # 或者你的主分支名
    paths:
      - 'forward/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: forward/package.json

      - name: Install Dependencies
        run: npm install
        working-directory: ./forward

      - name: Build
        run: npm run build
        working-directory: ./forward

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./forward/dist
          publish_branch: gh-pages